language: c
os: linux
dist: trusty
sudo: required

branches:
  only:
  - master
  - development
  - CI

addons:
  apt:
    packages:
    - libc6:i386
    - libncurses5:i386
    - libstdc++6:i386

before_install:
- git config --local user.name "Mrucznik"
- git config --local user.email "mrucznix@gmail.com"

before_script:
- chmod +x CI_scripts/*
- CI_scripts/get_compiler.sh
- cp -R include ~/compiler/

script:
- CI_scripts/compile.sh gamemodes/Mrucznik-RP.pwn

before_deploy:
- git tag "$(grep -oP '\#define\ \VERSION \"\K(.+)(?=\")' Mrucznik-RP.pwn) - $(date
  +'%d.%m.%Y') - $(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: tzPk0sBfvy2Pthc0QlpRaUTaJI4MNdEDHZ2FCQqczEusOdYNB3XgslkEa+ifA35MVD9fMG/K/AHuziGROkANX/B1x4WRoy7EihKlO+uc17s2otZfxG4R4qxw7RlST0mM4sLabWO1RNOXFcKl4w9HEWGb4MKMNUdRjjt2tw+U+eERQ1fi0aIobV0fP0mKdJ5eMmzNdwLC0nIIh+S6PGaZqnGgDe1Bs/ph8sITAxYoq8qG6zcA6xgF57BBR4J1xPTgufHRDMqduFw7uoV1Eya8xgk1H/y1JJYEvQ8T0NMgwFggD0TQkalLQ55pZZ0/yfvgR1ruy/Qpebng3Tu7NJGN2iC2IS/jCa+5Rwl9x0Qth1VwcgpsoWgDMo8UuEJD14hpBMMpUQEdpnJr+52R5rXTm4g+u1+fxCt8fUmLLS/u4AcWSDKEHKrEpBuj7r/PBWiQKjBdKbgjEUhWgUd+L+M1pBYRAAU553RcQplppWjIkpvL38C71Fxfg3YblzAjQrrfICN+USXEhZQUTlLhKzn2HSP6y9JH5RNsIjgh3j/74Mqr7pFkSKNuHtYnhFZ+2DZOKB8cIih8gF5IDO0f6/srOfTt/ugu0WNXKOFs3Yjn/wG1WviLu7Sz+scjzkufXzAZQOSQzBQ+NFuPEEyxUmypBcoyslzkYvOPFWybQmoeIBk=
  file: Mrucznik-RP.amx
  on:
    repo: Mrucznik/Mrucznik-RP-2.5
    branches:
      only:
      - master
      - development
      - CI
